Use brass from hades_extramaterials mod if aviable.
random-geek/morelights pull request #8
Opened 2021-12-20 07:22 UTC by sfence

hades_extramaterials is now part of modpack [hades_extensionmods](https://content.minetest.net/packages/SFENCE/hades_extensionmods/).

2021-12-20 22:28 UTC, random-geek requested changes
Looks good, will merge if the noted change is made.

2021-12-20 22:28 UTC, random-geek commented on morelights/init.lua
> +if minetest.get_modpath("hades_extramaterials") then
I suggest making this an `elseif`.

2021-12-21 14:56 UTC, sfence commented
Done.

2021-12-21 18:37 UTC, random-geek approved these changes

2021-12-21 18:38 UTC, merged